=== Elevate-IT/xslt/181 - Dandoy/Belchim/Proagrica/TandT_CPP_DespatchAdvice_v2018p01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 sp1 (http://www.altova.com) by Conny Graumans (AgroConnect) -->
<!--xsd Track & trace Crop Protection Products, Despatch Advice Message, AgroConnect, version v2018p01, last update 21okt21-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ttdesp="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01" xmlns:udt="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/UnqualifiedDataType_21p0" xmlns:cdt="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_DataTypes_v2018p01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01" elementFormDefault="qualified" attributeFormDefault="unqualified" version="8.0">
	<xsd:import namespace="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_DataTypes_v2018p01" schemaLocation="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_DataTypes_v2018p01.xsd"/>
	<xsd:import namespace="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/UnqualifiedDataType_21p0" schemaLocation="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/UnqualifiedDataType_21p0.xsd"/>
	<xsd:element name="MessageHeader" type="ttdesp:MessageHeaderType"/>
	<xsd:complexType name="MessageHeaderType">
		<xsd:sequence>
			<xsd:element name="MessageID" type="udt:IDType"/>
			<xsd:element name="SendingDateTime" type="udt:DateTimeType"/>
			<xsd:element name="SendingPartyID" type="udt:IDType"/>
			<xsd:element name="ReceivingPartyID" type="udt:IDType"/>
			<xsd:element name="MessageType" type="cdt:messageTypeCode"/>
			<xsd:element name="MessagePurposeCode" type="cdt:messagePurposeCodeCode"/>
			<xsd:element name="Delivery" type="ttdesp:DeliveryType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Delivery" type="ttdesp:DeliveryType"/>
	<xsd:complexType name="DeliveryType">
		<xsd:sequence>
			<xsd:element name="DeliveryID" type="udt:IDType"/>
			<xsd:element name="DeliveryStatusCode" type="cdt:documentStatusCode"/>
			<xsd:element name="OriginalDeliveryReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="DeliveryDateTime" type="udt:DateTimeType"/>
			<xsd:element name="GrossWeight" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="NetWeight" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="Volume" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="Timing" type="ttdesp:TimingType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Remark" type="ttdesp:RemarkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="MeansOfTransportation" type="ttdesp:MeansOfTransportationType" minOccurs="0"/>
			<xsd:element name="InternationalCommercialTerms" type="ttdesp:InternationalCommercialTermsType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="TradeParty" type="ttdesp:TradePartyType" maxOccurs="unbounded"/>
			<xsd:element name="DeliveryLine" type="ttdesp:DeliveryLineType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="TradeParty" type="ttdesp:TradePartyType"/>
	<xsd:complexType name="TradePartyType">
		<xsd:sequence>
			<xsd:element name="GlobalID" type="udt:IDType"/>
			<xsd:element name="LocalID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="ChamberOfCommerceNumber" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="TradePartyRoleCode" type="cdt:tradePartyRoleCode"/>
			<xsd:element name="TradePartyName" type="udt:TextType"/>
			<xsd:element name="StreetNameAndNumber" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PostalCodeLocation" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="CityName" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="CountryCode" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PostBoxNumber" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PostalCodePostBox" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="CityNamePostBox" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="CountryCodePostBox" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PhoneNumber" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="MobilePhoneNumber" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="TelefaxNumber" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="EmailAddress" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PersonToContact" type="udt:TextType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="InternationalCommercialTerms" type="ttdesp:InternationalCommercialTermsType"/>
	<xsd:complexType name="InternationalCommercialTermsType">
		<xsd:sequence>
			<xsd:element name="ICT_ReferenceID" type="udt:TextType"/>
			<xsd:element name="ICT_Description" type="udt:TextType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="MeansOfTransportation" type="ttdesp:MeansOfTransportationType"/>
	<xsd:complexType name="MeansOfTransportationType">
		<xsd:sequence>
			<xsd:element name="TransportMeansID" type="udt:IDType"/>
			<xsd:element name="TransportMeansTypeCode" type="cdt:transportMeansTypeCode"/>
			<xsd:element name="TransportMeansName" type="udt:TextType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Timing" type="ttdesp:TimingType"/>
	<xsd:complexType name="TimingType">
		<xsd:sequence>
			<xsd:element name="EventTypeCode" type="cdt:eventTypeCode"/>
			<xsd:element name="EventDateTime" type="udt:DateTimeType" minOccurs="0"/>
			<xsd:element name="EventBeginDateTime" type="udt:DateTimeType" minOccurs="0"/>
			<xsd:element name="EventEndDateTime" type="udt:DateTimeType" minOccurs="0"/>
			<xsd:element name="EventSequenceNumber" type="udt:NumericType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="DeliveryLine" type="ttdesp:DeliveryLineType"/>
	<xsd:complexType name="DeliveryLineType">
		<xsd:sequence>
			<xsd:element name="DeliveryLineID" type="udt:IDType"/>
			<xsd:element name="DeliveryLineQuantity" type="udt:MeasureType"/>
			<xsd:element name="OrderReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="OrderLineReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="EndCustomerOrderReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="EndCustomerOrderLineReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="Remark" type="ttdesp:RemarkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProductUnit" type="ttdesp:ProductUnitType"/>
			<xsd:element name="Timing" type="ttdesp:TimingType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="PackageProductUnitFirstLevel" type="ttdesp:PackageProductUnitFirstLevelType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ProductUnit" type="ttdesp:ProductUnitType"/>
	<xsd:complexType name="ProductUnitType">
		<xsd:sequence>
			<xsd:element name="ProductUnitID_SSCC" type="udt:IDType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Is not relevant for the Order message, only for the Delivery message.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ProductUnitID_GTIN" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="ProductUnitTypeCode" type="cdt:productUnitTypeCode"/>
			<xsd:element name="BatchID" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="SupplierProductUnitID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="OrdererProductUnitID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="ProductUnitName" type="udt:TextType" minOccurs="0"/>
			<xsd:element name="PackageTypeCode" type="cdt:packageTypeCode" minOccurs="0"/>
			<xsd:element name="SerialNumber" type="udt:TextType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProductionDate" type="udt:DateTimeType" minOccurs="0"/>
			<xsd:element name="PacketSize" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="GrossWeight" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="NetWeight" type="udt:MeasureType" minOccurs="0"/>
			<xsd:element name="ExpiryDate" type="udt:DateTimeType" minOccurs="0"/>
			<xsd:element name="RegionalRegistrationID" type="udt:IDType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PackageProductUnitFirstLevelType">
		<xsd:sequence>
			<xsd:element name="Quantity" type="udt:NumericType" minOccurs="0"/>
			<xsd:element name="OrderReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="OrderLineReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="Remark" type="ttdesp:RemarkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProductUnit" type="ttdesp:ProductUnitType" minOccurs="1"/>
			<xsd:element name="PackageProductUnitSecondLevel" type="ttdesp:PackageProductUnitSecondLevelType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PackageProductUnitSecondLevelType">
		<xsd:sequence>
			<xsd:element name="Quantity" type="udt:NumericType" minOccurs="0"/>
			<xsd:element name="OrderReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="OrderLineReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="Remark" type="ttdesp:RemarkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProductUnit" type="ttdesp:ProductUnitType" minOccurs="1"/>
			<xsd:element name="PackageProductUnitThirdLevel" type="ttdesp:PackageProductUnitThirdLevelType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PackageProductUnitThirdLevelType">
		<xsd:sequence>
			<xsd:element name="Quantity" type="udt:NumericType" minOccurs="0"/>
			<xsd:element name="OrderReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="OrderLineReferenceID" type="udt:IDType" minOccurs="0"/>
			<xsd:element name="Remark" type="ttdesp:RemarkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProductUnit" type="ttdesp:ProductUnitType" minOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Remark" type="ttdesp:RemarkType"/>
	<xsd:complexType name="RemarkType">
		<xsd:sequence>
			<xsd:element name="TextFunctionTypeCode" type="cdt:textFunctionTypeCode"/>
			<xsd:element name="TextLines" type="udt:TextType"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Elevate-IT/xslt/181 - Dandoy/Actura/Track & Trace Project Pro Agrica/ProAgrica/Example TandT_CPP_DespatchAdvice_Farmusol_HollandFyto_3jul18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Example TandT_CPP_DespatchAdvice_Farmusol_HollandFyto_11feb19 by Conny Graumans (AgroConnect) -->
<ttdesp:MessageHeader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ttdesp="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01" xsi:schemaLocation="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01 http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01.xsd">
	<ttdesp:MessageID schemeID="REF">MES123456</ttdesp:MessageID>
	<ttdesp:SendingDateTime>2018-07-01T09:30:47Z</ttdesp:SendingDateTime>
	<ttdesp:SendingPartyID schemeID="GLN">8719333007229</ttdesp:SendingPartyID><!--GLN Farmusol-->
	<ttdesp:ReceivingPartyID schemeID="GLN">8719324290005</ttdesp:ReceivingPartyID><!--GLN Holland Fyto-->
	<ttdesp:MessageType>102</ttdesp:MessageType><!-- = Deliver-->
	<ttdesp:MessagePurposeCode>47</ttdesp:MessagePurposeCode><!--47= for production, definitive-->
	<ttdesp:Delivery>
		<ttdesp:DeliveryID schemeID="REF">DEL234567</ttdesp:DeliveryID><!--Generated by Farmusol-->
		<ttdesp:DeliveryStatusCode>101</ttdesp:DeliveryStatusCode><!--101= original-->
		<ttdesp:DeliveryDateTime>2018-10-10T09:30:47Z</ttdesp:DeliveryDateTime>
		<ttdesp:GrossWeight unitCode="KGM">2000</ttdesp:GrossWeight>
		<ttdesp:NetWeight unitCode="KGM">1800</ttdesp:NetWeight>
		<ttdesp:Timing>
			<ttdesp:EventTypeCode>101</ttdesp:EventTypeCode><!-- = Load-->
			<ttdesp:EventDateTime>2018-07-10T09:30:47Z</ttdesp:EventDateTime>
		</ttdesp:Timing>
		<ttdesp:Timing>
			<ttdesp:EventTypeCode>102</ttdesp:EventTypeCode><!-- = Deliver-->
			<ttdesp:EventDateTime>2018-07-10T14:30:47Z</ttdesp:EventDateTime>
		</ttdesp:Timing>
		<ttdesp:Remark>
			<ttdesp:TextFunctionTypeCode>103</ttdesp:TextFunctionTypeCode><!-- = DeliverInstruction-->
			<ttdesp:TextLines>2Loods 13, stelling 5</ttdesp:TextLines>
		</ttdesp:Remark>
		<ttdesp:MeansOfTransportation>
			<ttdesp:TransportMeansID schemeID="NUMMERPLAAT">82-ABC-89</ttdesp:TransportMeansID>
			<ttdesp:TransportMeansTypeCode>36</ttdesp:TransportMeansTypeCode><!-- = Truck, dry bulk-->
		</ttdesp:MeansOfTransportation>
		<ttdesp:InternationalCommercialTerms>
			<ttdesp:ICT_ReferenceID>Ref EU2356</ttdesp:ICT_ReferenceID>
			<ttdesp:ICT_Description>Volgens Europese regelgeving.</ttdesp:ICT_Description>
		</ttdesp:InternationalCommercialTerms>
		<ttdesp:TradeParty>
			<ttdesp:GlobalID schemeID="GLN">8719333007229</ttdesp:GlobalID><!--Farmusol-->
			<ttdesp:TradePartyRoleCode>SF</ttdesp:TradePartyRoleCode><!--= ShippedFrom-->
			<ttdesp:TradePartyName>Farmusol B.V.</ttdesp:TradePartyName>
			<ttdesp:StreetNameAndNumber>Industriestraat 10</ttdesp:StreetNameAndNumber>
			<ttdesp:PostalCodeLocation>6827BD</ttdesp:PostalCodeLocation>
			<ttdesp:CityName>Arnhem</ttdesp:CityName>
			<ttdesp:CountryCode>NL</ttdesp:CountryCode>
			<ttdesp:PersonToContact>Floris Rhemrev</ttdesp:PersonToContact>
		</ttdesp:TradeParty>	
		<ttdesp:TradeParty>
			 <ttdesp:GlobalID schemeID="GLN">8719324290005</ttdesp:GlobalID><!--GLN Holland Fyto-->
			 <ttdesp:TradePartyRoleCode>ST</ttdesp:TradePartyRoleCode><!--= ShippedTo-->
			 <ttdesp:TradePartyName>Holland Fyto</ttdesp:TradePartyName>
			 <ttdesp:PostBoxNumber>Postbus 1077</ttdesp:PostBoxNumber>
			 <ttdesp:PostalCodePostBox>8300 BB</ttdesp:PostalCodePostBox>
			 <ttdesp:CityNamePostBox>EMMELOORD</ttdesp:CityNamePostBox>
			 <ttdesp:CountryCodePostBox>NLD</ttdesp:CountryCodePostBox>
		</ttdesp:TradeParty>
		<ttdesp:DeliveryLine>
			<ttdesp:DeliveryLineID schemeID="REF">Nr123456</ttdesp:DeliveryLineID>
			<ttdesp:DeliveryLineQuantity unitCode="NBR">1</ttdesp:DeliveryLineQuantity><!--in this case 1 pallet-->
			<ttdesp:OrderReferenceID schemeID="REF">Ordernr12345</ttdesp:OrderReferenceID>
			<ttdesp:OrderLineReferenceID schemeID="REF">Orderlinenr12345667</ttdesp:OrderLineReferenceID>
			<ttdesp:ProductUnit>
				<ttdesp:ProductUnitID_SSCC schemeID="SSCC">4896512765432</ttdesp:ProductUnitID_SSCC><!--SSCC of the pallet-->
				<ttdesp:ProductUnitTypeCode>101</ttdesp:ProductUnitTypeCode><!-- = LogisticUnit-->
				<ttdesp:ProductUnitName>Pallet Captosan</ttdesp:ProductUnitName>
				<ttdesp:PackageTypeCode>PA</ttdesp:PackageTypeCode><!-- = Pallet-->
				<ttdesp:ProductionDate>2017-12-17T09:30:47Z</ttdesp:ProductionDate>
			</ttdesp:ProductUnit>
			<ttdesp:PackageProductUnitFirstLevel>
				<ttdesp:Quantity>10</ttdesp:Quantity><!--number of TradeUnits Captosan on the pallet-->
				<ttdesp:ProductUnit>
					<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077002453</ttdesp:ProductUnitID_GTIN>
					<ttdesp:ProductUnitTypeCode>102</ttdesp:ProductUnitTypeCode><!-- = TradeUnit-->
					<ttdesp:BatchID>34781289</ttdesp:BatchID>
					<ttdesp:ProductUnitName>Box Captosan 500 SC</ttdesp:ProductUnitName>
					<ttdesp:PackageTypeCode>BX</ttdesp:PackageTypeCode><!-- = Box-->
					<ttdesp:ProductionDate>2017-12-17T09:30:47Z</ttdesp:ProductionDate>
				</ttdesp:ProductUnit>
				<ttdesp:PackageProductUnitSecondLevel>
					<ttdesp:Quantity>8</ttdesp:Quantity><!--number of ConsumerUnits in each TradeUnit-->
					<ttdesp:ProductUnit>
						<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077002446</ttdesp:ProductUnitID_GTIN>
						<ttdesp:ProductUnitTypeCode>103</ttdesp:ProductUnitTypeCode><!-- = ConsumerUnit-->
						<ttdesp:BatchID>34781289</ttdesp:BatchID>
						<ttdesp:ProductUnitName>Captosan 500 SC</ttdesp:ProductUnitName>
						<ttdesp:PackageTypeCode>BO</ttdesp:PackageTypeCode><!-- = Bottle-->
						<ttdesp:SerialNumber>PROD345678</ttdesp:SerialNumber>
						<ttdesp:ProductionDate>2017-12-31T09:30:47Z</ttdesp:ProductionDate>
						<ttdesp:ExpiryDate>2020-12-17T09:30:47Z</ttdesp:ExpiryDate>
					</ttdesp:ProductUnit>
				</ttdesp:PackageProductUnitSecondLevel>
			</ttdesp:PackageProductUnitFirstLevel>
			<ttdesp:PackageProductUnitFirstLevel>
				<ttdesp:Quantity>5</ttdesp:Quantity><!--number of TradeUnits ProductX on the pallet-->
				<ttdesp:ProductUnit>
					<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077002999</ttdesp:ProductUnitID_GTIN>
					<ttdesp:ProductUnitTypeCode>102</ttdesp:ProductUnitTypeCode><!-- = TradeUnit-->
					<ttdesp:BatchID>34786789</ttdesp:BatchID>
					<ttdesp:ProductUnitName>Box with 6 ProduxtX ConsumerUnits</ttdesp:ProductUnitName>
					<ttdesp:PackageTypeCode>BX</ttdesp:PackageTypeCode><!-- = Box-->
					<ttdesp:ProductionDate>2017-12-17T09:30:47Z</ttdesp:ProductionDate>
					<ttdesp:ExpiryDate>2020-12-17T09:30:47Z</ttdesp:ExpiryDate>
				</ttdesp:ProductUnit>
				<ttdesp:PackageProductUnitSecondLevel>
					<ttdesp:Quantity>4</ttdesp:Quantity><!--number of ConsumerUnits in each TradeUnit-->
					<ttdesp:ProductUnit>
						<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077003999</ttdesp:ProductUnitID_GTIN>
						<ttdesp:ProductUnitTypeCode>103</ttdesp:ProductUnitTypeCode><!-- = ConsumerUnit-->
						<ttdesp:BatchID>34781289</ttdesp:BatchID>
						<ttdesp:ProductUnitName>Bottle ProductX</ttdesp:ProductUnitName>
						<ttdesp:PackageTypeCode>BO</ttdesp:PackageTypeCode><!-- = Bottle-->
						<ttdesp:SerialNumber>PROD345678</ttdesp:SerialNumber>
						<ttdesp:ProductionDate>2017-12-31T09:30:47Z</ttdesp:ProductionDate>
						<ttdesp:ExpiryDate>2020-12-17T09:30:47Z</ttdesp:ExpiryDate>
					</ttdesp:ProductUnit>
				</ttdesp:PackageProductUnitSecondLevel>
			</ttdesp:PackageProductUnitFirstLevel>
		</ttdesp:DeliveryLine>
	</ttdesp:Delivery>
</ttdesp:MessageHeader>

=== Elevate-IT/xslt/181 - Dandoy/Actura/Track & Trace Project Pro Agrica/ProAgrica/190311.Voorbeelden voor 13mrt19/Example TT_CPP_Farmusol_HollandFyto_HomPal_28feb19_DA_0000330601.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Example DespatchAdvice homogenious pallet from Farmusol to Holland Fyto-->
<ttdesp:MessageHeader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ttdesp="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01" xsi:schemaLocation="http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01 http://www.agroconnect.nl/Portals/10/XSDs/TandT_CPP/v2018p01/TandT_CPP_DespatchAdvice_v2018p01.xsd">
	<ttdesp:MessageID schemeID="REF">DA_0000330601</ttdesp:MessageID>
	<ttdesp:SendingDateTime>2019-03-04T09:30:47Z</ttdesp:SendingDateTime>
	<ttdesp:SendingPartyID schemeID="GLN">8719333007229</ttdesp:SendingPartyID><!--GLN Farmusol-->
	<ttdesp:ReceivingPartyID schemeID="GLN">8719324290005</ttdesp:ReceivingPartyID><!--GLN Holland Fyto-->
	<ttdesp:MessageType>102</ttdesp:MessageType><!-- = Deliver-->
	<ttdesp:MessagePurposeCode>47</ttdesp:MessagePurposeCode><!--47= for production, definitive-->
	<ttdesp:Delivery>
		<ttdesp:DeliveryID schemeID="REF">DA_0000330601</ttdesp:DeliveryID><!--Generated by Farmusol-->
		<ttdesp:DeliveryStatusCode>101</ttdesp:DeliveryStatusCode><!--101= original-->
		<ttdesp:DeliveryDateTime>2019-03-15T12:00:00Z</ttdesp:DeliveryDateTime>
		<ttdesp:Timing>
			<ttdesp:EventTypeCode>101</ttdesp:EventTypeCode><!-- = Load-->
			<ttdesp:EventDateTime>2019-03-15T09:30:00Z</ttdesp:EventDateTime>
		</ttdesp:Timing>
		<ttdesp:Timing>
			<ttdesp:EventTypeCode>102</ttdesp:EventTypeCode><!-- = Deliver-->
			<ttdesp:EventDateTime>2019-03-15T11:30:00Z</ttdesp:EventDateTime>
		</ttdesp:Timing>
		<ttdesp:Remark>
			<ttdesp:TextFunctionTypeCode>103</ttdesp:TextFunctionTypeCode><!-- = DeliverInstruction-->
			<ttdesp:TextLines>2Loods 13, stelling 5</ttdesp:TextLines>
		</ttdesp:Remark>
		<ttdesp:MeansOfTransportation>
			<ttdesp:TransportMeansID schemeID="NUMMERPLAAT">82-ABC-89</ttdesp:TransportMeansID>
			<ttdesp:TransportMeansTypeCode>36</ttdesp:TransportMeansTypeCode><!-- = Truck, dry bulk-->
		</ttdesp:MeansOfTransportation>
		<ttdesp:InternationalCommercialTerms>
			<ttdesp:ICT_ReferenceID>Ref EU2356</ttdesp:ICT_ReferenceID>
			<ttdesp:ICT_Description>Volgens Europese regelgeving.</ttdesp:ICT_Description>
		</ttdesp:InternationalCommercialTerms>
		<ttdesp:TradeParty>
			<ttdesp:GlobalID schemeID="GLN">8719333007229</ttdesp:GlobalID><!--Farmusol-->
			<ttdesp:TradePartyRoleCode>SF</ttdesp:TradePartyRoleCode><!--= ShippedFrom-->
			<ttdesp:TradePartyName>Farmusol B.V.</ttdesp:TradePartyName>
			<ttdesp:StreetNameAndNumber>Industriestraat 10</ttdesp:StreetNameAndNumber>
			<ttdesp:PostalCodeLocation>6827BD</ttdesp:PostalCodeLocation>
			<ttdesp:CityName>Arnhem</ttdesp:CityName>
			<ttdesp:CountryCode>NL</ttdesp:CountryCode>
			<ttdesp:PersonToContact>Floris Rhemrev</ttdesp:PersonToContact>
		</ttdesp:TradeParty>	
		<ttdesp:TradeParty>
			 <ttdesp:GlobalID schemeID="GLN">8719324290005</ttdesp:GlobalID><!--GLN Holland Fyto-->
			 <ttdesp:TradePartyRoleCode>ST</ttdesp:TradePartyRoleCode><!--= ShippedTo-->
			 <ttdesp:TradePartyName>Holland Fyto</ttdesp:TradePartyName>
			 <ttdesp:PostBoxNumber>Postbus 1077</ttdesp:PostBoxNumber>
			 <ttdesp:PostalCodePostBox>8300 BB</ttdesp:PostalCodePostBox>
			 <ttdesp:CityNamePostBox>EMMELOORD</ttdesp:CityNamePostBox>
			 <ttdesp:CountryCodePostBox>NLD</ttdesp:CountryCodePostBox>
		</ttdesp:TradeParty>
      <ttdesp:DeliveryLine>
         <ttdesp:DeliveryLineID schemeID="REF">TO0000330401-0001</ttdesp:DeliveryLineID>
         <ttdesp:DeliveryLineQuantity unitCode="NBR">1</ttdesp:DeliveryLineQuantity><!--1 pallet-->
         <ttdesp:ProductUnit>
			<ttdesp:ProductUnitID_SSCC schemeID="SSCC">4896512765432</ttdesp:ProductUnitID_SSCC><!--SSCC of the pallet-->
			<ttdesp:ProductUnitTypeCode>101</ttdesp:ProductUnitTypeCode><!--= LogisticUnit-->
            <ttdesp:ProductUnitName>Uniforme pallet pallet Goltix SC (600 liter/30 trade units/120 consumer units)</ttdesp:ProductUnitName>
			<ttdesp:PackageTypeCode>PA</ttdesp:PackageTypeCode><!--= pallet-->
         </ttdesp:ProductUnit>
		<ttdesp:PackageProductUnitFirstLevel>
			<ttdesp:Quantity>30</ttdesp:Quantity><!--number of TradeUnits on the pallet-->
			<ttdesp:ProductUnit>
				<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077002156</ttdesp:ProductUnitID_GTIN>
				<ttdesp:ProductUnitTypeCode>102</ttdesp:ProductUnitTypeCode><!-- = TradeUnit-->
				<ttdesp:BatchID>1901030567</ttdesp:BatchID>
				<ttdesp:ProductUnitName>Goltix SC</ttdesp:ProductUnitName>
				<ttdesp:PackageTypeCode>JY</ttdesp:PackageTypeCode><!--= Jerrican, cylindrical-->
				<ttdesp:ProductionDate>2019-01-10T09:30:47Z</ttdesp:ProductionDate>
			</ttdesp:ProductUnit>
		</ttdesp:PackageProductUnitFirstLevel>            
      </ttdesp:DeliveryLine>
      <ttdesp:DeliveryLine>
         <ttdesp:DeliveryLineID schemeID="REF">TO0000330401-0002</ttdesp:DeliveryLineID>
         <ttdesp:DeliveryLineQuantity unitCode="NBR">1</ttdesp:DeliveryLineQuantity><!--1 pallet-->
         <ttdesp:ProductUnit>
			<ttdesp:ProductUnitID_SSCC schemeID="SSCC">4896512765589</ttdesp:ProductUnitID_SSCC><!--SSCC of the pallet-->
            <ttdesp:ProductUnitTypeCode>101</ttdesp:ProductUnitTypeCode><!--= LogisticUnit-->
            <ttdesp:ProductUnitName>Uniforme pallet Mirador Xtra (600 liter/30 trade units/120 consumer units)</ttdesp:ProductUnitName>
			<ttdesp:PackageTypeCode>PA</ttdesp:PackageTypeCode><!--= pallet-->
         </ttdesp:ProductUnit>
		<ttdesp:PackageProductUnitFirstLevel>
			<ttdesp:Quantity>30</ttdesp:Quantity><!--number of TradeUnits on the pallet-->
			<ttdesp:ProductUnit>
				<ttdesp:ProductUnitID_GTIN schemeID="GTIN">08718077012896</ttdesp:ProductUnitID_GTIN>
				<ttdesp:ProductUnitTypeCode>102</ttdesp:ProductUnitTypeCode><!-- = TradeUnit-->
				<ttdesp:BatchID>1901010032</ttdesp:BatchID>
				<ttdesp:ProductUnitName>Mirador Xtra</ttdesp:ProductUnitName>
				<ttdesp:PackageTypeCode>JY</ttdesp:PackageTypeCode><!--= Jerrican, cylindrical-->
				<ttdesp:ProductionDate>2019-01-24T09:30:47Z</ttdesp:ProductionDate>
			</ttdesp:ProductUnit>
		</ttdesp:PackageProductUnitFirstLevel> 
      </ttdesp:DeliveryLine>
	</ttdesp:Delivery>
</ttdesp:MessageHeader>
